[package]
name = "mvc"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = true

[dependencies]
bytebuffer = "2.1.1"
hashbrown = "0.13.2"
mvutils = { path = "../MVUtils" }
phf = { version = "0.11.1", features = ["macros"] }
